function createfigure(X1, YMatrix1, ZMatrix1)
%CREATEFIGURE(X1,YMATRIX1,ZMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data

%  Auto-generated by MATLAB on 12-Jul-2007 16:52:50

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1,'ZGrid','on','XGrid','on','FontSize',8,...
    'FontAngle','italic');
view([-17.5 86]);
hold('all');

% Create multiple lines using matrix input to plot3
plot31 = plot3(X1,YMatrix1,ZMatrix1,'LineWidth',2);
set(plot31(1),'DisplayName','Desired velocity','Color',[0.8 0 0.6]);
set(plot31(2),'DisplayName','Vehicle velocity');
set(plot31(3),'DisplayName','Local verdict','LineWidth',0.5);

% Create xlabel
xlabel('time');

% Create ylabel
ylabel('velocity');

% Create zlabel
zlabel({' Local','verdict'});

% Create title
title('Test execution results for speed controller');

% Create legend
legend(axes1,'show');

